Added week2_classExs CALCULATOR METHOD and DISTINCT APPHABETICAL LIST
sumanghimire79/hyf-dotnet-masterclass pull request #2
Opened 2023-03-02 19:57 UTC by sumanghimire79

2023-03-02 21:22 UTC, Vertygo commented on week2/week2_classExs/Program.cs
> +  int AddNumbers(int parsedInput)
This method is inside the endpoint method. And this kind of method (method inside of the method) is called the [local function](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions) (yes, it's not called local method 🙈 ). Also, this function can't be called outside of its parent method. We will maybe cover/mention this in our next class.

2023-03-02 21:27 UTC, Vertygo commented on week2/week2_classExs/Program.cs
> +  List<char> test_list = new List<char>();
In C# it is common to use `camelCase` for the name of variable.

2023-03-02 21:29 UTC, Vertygo requested changes
These three are exercises but please finish also homework [homework](https://github.com/HackYourFuture-CPH/dotnet-masterclass/blob/main/week2/homework.md) for this week.

2023-03-03 08:09 UTC, sumanghimire79 commented on week2/week2_classExs/Program.cs
> +  List<char> test_list = new List<char>();
i fixed it to camelCase. thank you

2023-03-05 20:15 UTC, Vertygo approved these changes

2023-03-15 13:53 UTC, sumanghimire79 commented on week2/week2_classExs/Program.cs
> +  int AddNumbers(int parsedInput)
ok !!

2023-03-23 17:04 UTC, merged